version: 2.0

machine:
  environment:
    PROJECT_NAME: deploy-test
    CLUSTER_NAME: hello-cluster	
    CLOUDSDK_COMPUTE_ZONE: us-central1-a
    DEBIAN_FRONTEND: noninteractive
  services:
    - docker

jobs:
    product:
        machine: true
        steps:
            - checkout
            - run: echo "product!!"
            - run: chmod 777 ./.circleci/product.deploy.sh
            - run: bash ./.circleci/product.deploy.sh
workflows:
    version: 2
    test_and_deploy:
        jobs:
            - product:
                context: deploy-test
                filters:
                    branches:
                        only: develop

